---
- name: Ensure PostgreSQL databases are present.
  postgresql_db:
    name: "{{ item}}"
    owner: "{{ postgresql_user | default(postgresql_user) }}"
  with_items: "{{ postgresql_databases }}"
  become: yes
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
