- name: MySql Jar Downloading zip 5.1.34
  get_url:
    url: https://downloads.mysql.com/archives/get/file/mysql-connector-java-5.1.34.zip
    dest: /tmp
  tags: install.jar

- name: "Downloading the API package and Unzip 5.1.34"
  unarchive:
    src: /tmp/mysql-connector-java-5.1.34.zip
    remote_src: yes 
    dest: /tmp
  tags: install.jar

- name: "Copying the Jar Files EI"
  copy:
    src: /tmp/mysql-connector-java-5.1.34/mysql-connector-java-5.1.34-bin.jar
    remote_src: yes 
    dest: "{{ EI_Home}}/lib"
    owner: "{{ app_user }}" 
    group: "{{ app_user }}"
    mode: 0740
  when: product == "EI"
  tags: install.jar

- name: "Copying the Jar Files API"
  copy:
    src: /tmp/mysql-connector-java-5.1.34/mysql-connector-java-5.1.34-bin.jar
    remote_src: yes 
    dest: "{{ API_Home}}/wso2am-2.1.0/repository/components/lib"
    owner: "{{ app_user }}" 
    group: "{{ app_user }}"
    mode: 0740
  when: product == "API"
  tags: install.jar

- name: Removing the Mysql Downloads
  file: dest=/tmp/{{ item }} state=absent
  with_items:
    - mysql-connector-java-5.1.34
    - mysql-connector-java-5.1.34.zip
  when: product == "EI"
  tags: install.jar