---

  - name: "Installing unzip | RedHat"
    yum: 
      name: unzip
      state: latest
    when: ansible_os_family == 'RedHat'
    tags: install.ei

  - name: "Installing unzip | Debian"
    apt:
      pkg: unzip
      state: latest
    when: ansible_os_family == 'Debian'
    tags: install.ei

  - name: get the hostname
    command: "hostname"
    register: command_output
    tags: install.host

  - set_fact:
      localhostname: "{{ command_output.stdout }}"
    tags: install.host

  - name: "Adding hostname to localhost "
    blockinfile:
      path: /etc/hosts
      block: |
        127.0.0.1  {{ localhostname }}
      insertafter: EOF 
    tags: install.host

  - import_tasks: user.yml
    tags: install.ei

  - name: "Making the Home Path"
    file: 
      dest: /opt/EI
      mode: 0775 
      owner: "{{ app_user }}"
      group: "{{ app_user }}"
      state: directory
    tags: install.ei

  - name: Download EI with custom HTTP headers
    get_url:
      url: https://product-dist.wso2.com/products/enterprise-integrator/6.1.1/wso2ei-6.1.1.zip
      dest: /tmp
      headers: 'user-agent:"testuser",referer:http://connect.wso2.com/wso2/getform/reg/new_product_download'
    tags: install.ei

  - name: "Unziping the EI to Home path"
    unarchive:
      src: /tmp/wso2ei-6.1.1.zip
      remote_src: yes
      dest: /opt/EI
      owner: "{{ app_user }}" 
      group: "{{ app_user }}"
    tags: install.ei

  - name: Removing the APIMAnager Downloads
    file:
      dest: /tmp//wso2ei-6.1.1.zip
      state: absent
    tags: install.ei
    
  - name: "Making the Product home path | Debian"
    blockinfile:
      path: ~/.bashrc
      block: |
        export JAVA_HOME=/usr/lib/jvm/java-8-oracle
        export PATH=${JAVA_HOME}/bin:${PATH}
        export EI_HOME=/opt/EI/wso2ei-6.1.1
        export PATH=${EI_HOME}/bin:${PATH}
      insertafter: EOF 
    when: ansible_os_family == 'Debian'
    tags: install.java.env

  - name: "Making the Product home path | RedHat"
    blockinfile:
      path: ~/.bashrc
      block: |
        export JAVA_HOME=/usr/java/jdk1.8.0_172-amd64/jre
        export PATH=${JAVA_HOME}/bin:${PATH}
        export EI_HOME=/opt/EI/wso2ei-6.1.1
        export PATH=${EI_HOME}/bin:${PATH}
      insertafter: EOF 
    when: ansible_os_family == 'RedHat'
    tags: install.java.env

  - import_tasks: tuning.yml
    tags: install.ei.configurations