---

- name: Ensure lxml python library installed
  pip:
    name: lxml
    state: latest
  tags: install.api.configurations

- name: Setting Commpression off to Due to a bug 
  xml:
    path: /opt/API_Manager/wso2am-2.1.0/repository/conf/tomcat/catalina-server.xml
    xpath: /Server/Service/Connector
    attribute: compression
    value: "off"
    pretty_print: yes
  tags: install.api.configurations