---

  # Variable configuration.
  - import_tasks: variables.yml
    tags: install.mysql, install.mysql.secure, manage:db, manage:db.user, manage:db.table.api, manage:db.table.ei

  # Setup/install tasks.
  - import_tasks: setup-RedHat.yml
    when: ansible_os_family == 'RedHat'
    tags: install.mysql

  - import_tasks: setup-Debian.yml
    when: ansible_os_family == 'Debian'
    tags: install.mysql

  - name: Ensure MySQL is started and enabled on boot.
    service:
      name: "{{ mysql_daemon }}"
      state: started"
      enabled: yes
    tags: install.mysql

  # MySQL secure installation
  - name: remove the test database
    mysql_db:
      name: test
      state: absent
    tags: install.mysql.secure

  - name: Removes anonymous user account for localhost
    mysql_user:
      name: ''
      host: localhost
      state: absent
    tags: install.mysql.secure

  - name: Disallow root login remotely
    command: 'mysql -NBe "{{ item }}"'
    with_items:
      - DELETE FROM mysql.user WHERE User='{{ mysql_root_username }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    changed_when: false
    tags: install.mysql.secure

  - name: update mysql root password for all root accounts
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_pass }}"
    with_items:
      - 127.0.0.1
      - ::1
      - localhost
    tags: install.mysql.secure

  # DB setup, create users and grant permission
  - name: Create MySQL databases.
    mysql_db:
      name: "{{ item }}"
      state: "present"
    with_items: "{{ mysql_databases }}"
    tags: manage:db

  - name: Create database users
    mysql_user: 
      user: "{{ item }}" 
      password: "{{ mysql_users_pass }}"
      host: "%"
      priv: "*.*:ALL" 
      state: "present"
    with_items: "{{ mysql_users }}"
    tags: manage:db.user
